"""
Synthetic Data Generator. Generates book catalog data.
"""

import json
import os
import random
import re
import uuid
from typing import Any, Dict, List

from loguru import logger


def sanitize_filename(title: str) -> str:
    """Convert the title to a safe filename (must match download_covers.py)."""
    filename = re.sub(r"[^\w\s-]", "", title.lower())
    filename = re.sub(r"\s+", "_", filename)
    return filename[:50]


random.seed(42)


# Popular children's books with metadata
BOOK_DATABASE = [
    # Fantasy
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J.K. Rowling",
        "genre": "Fantasy",
        "themes": ["magic", "friendship", "heroism"],
        "reading_level": "6-8",
        "pages": 309,
        "description": "An orphan boy discovers he's a wizard and attends Hogwarts School of Witchcraft and Wizardry, where he makes loyal friends and uncovers the truth about his parents' mysterious deaths.",
    },
    {
        "title": "Percy Jackson: The Lightning Thief",
        "author": "Rick Riordan",
        "genre": "Fantasy",
        "themes": ["mythology", "identity", "adventure"],
        "reading_level": "6-8",
        "pages": 377,
        "description": "A twelve-year-old with ADHD and dyslexia discovers he's the son of Poseidon and must journey across America to prevent a war among the Greek gods.",
    },
    {
        "title": "Aru Shah and the End of Time",
        "author": "Roshani Chokshi",
        "genre": "Fantasy",
        "themes": ["mythology", "identity", "family"],
        "reading_level": "6-8",
        "pages": 368,
        "description": "Twelve-year-old Aru accidentally frees an ancient demon by lighting a cursed lamp and must journey through Hindu mythology to save her mother and the world.",
    },
    {
        "title": "Howl's Moving Castle",
        "author": "Diana Wynne Jones",
        "genre": "Fantasy",
        "themes": ["magic", "courage", "love"],
        "reading_level": "6-8",
        "pages": 336,
        "description": "A young hat-maker cursed into an old woman's body seeks help from the mysterious wizard Howl, whose castle walks across the hills on chicken legs.",
    },
    {
        "title": "Eragon",
        "author": "Christopher Paolini",
        "genre": "Fantasy",
        "themes": ["heroism", "adventure", "magic"],
        "reading_level": "9-12",
        "pages": 509,
        "description": "A farm boy discovers a mysterious blue stone that hatches into a dragon, thrusting him into an ancient war against an evil king.",
    },
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "genre": "Fantasy",
        "themes": ["adventure", "courage", "heroism"],
        "reading_level": "6-8",
        "pages": 310,
        "description": "Homebody hobbit Bilbo Baggins is swept into an epic quest with thirteen dwarves to reclaim their mountain home from the dragon Smaug.",
    },
    {
        "title": "A Wizard of Earthsea",
        "author": "Ursula K. Le Guin",
        "genre": "Fantasy",
        "themes": ["identity", "magic", "coming-of-age"],
        "reading_level": "6-8",
        "pages": 183,
        "description": "Young wizard Ged must hunt down and face a terrifying shadow creature he accidentally unleashed while showing off his magical powers.",
    },
    {
        "title": "The Name of the Wind",
        "author": "Patrick Rothfuss",
        "genre": "Fantasy",
        "themes": ["magic", "mystery", "coming-of-age"],
        "reading_level": "9-12",
        "pages": 662,
        "description": "A legendary hero-turned-innkeeper recounts his journey from orphaned street urchin to the most notorious wizard in history.",
    },
    {
        "title": "Children of Blood and Bone",
        "author": "Tomi Adeyemi",
        "genre": "Fantasy",
        "themes": ["magic", "identity", "heroism"],
        "reading_level": "9-12",
        "pages": 544,
        "description": "In a world where magic has been violently suppressed, a young woman fights to restore her people's powers and overthrow a ruthless monarchy.",
    },
    {
        "title": "The Girl Who Drank the Moon",
        "author": "Kelly Barnhill",
        "genre": "Fantasy",
        "themes": ["magic", "family", "identity"],
        "reading_level": "6-8",
        "pages": 386,
        "description": "A kind witch accidentally feeds starlight and moonlight to a baby, filling her with extraordinary magic that she must learn to control.",
    },
    {
        "title": "Nevermoor: The Trials of Morrigan Crow",
        "author": "Jessica Townsend",
        "genre": "Fantasy",
        "themes": ["magic", "friendship", "identity"],
        "reading_level": "6-8",
        "pages": 451,
        "description": "A cursed girl escapes her fate by fleeing to a magical city where she must compete in dangerous trials to join a secret society.",
    },
    {
        "title": "The School for Good and Evil",
        "author": "Soman Chainani",
        "genre": "Fantasy",
        "themes": ["friendship", "identity", "magic"],
        "reading_level": "6-8",
        "pages": 488,
        "description": "Two best friends are kidnapped to a school where students train to become fairy tale heroes and villains, but they're placed in the wrong schools.",
    },
    # Science Fiction
    {
        "title": "Ender's Game",
        "author": "Orson Scott Card",
        "genre": "Science Fiction",
        "themes": ["technology", "identity", "heroism"],
        "reading_level": "9-12",
        "pages": 324,
        "description": "A brilliant child is recruited to a space battle school where he trains in zero-gravity war games to prepare for an alien invasion.",
    },
    {
        "title": "A Wrinkle in Time",
        "author": "Madeleine L'Engle",
        "genre": "Science Fiction",
        "themes": ["family", "love", "courage"],
        "reading_level": "6-8",
        "pages": 256,
        "description": "Meg Murry and her genius brother travel through space and time using a tesseract to rescue their scientist father from an evil force.",
    },
    {
        "title": "The Giver",
        "author": "Lois Lowry",
        "genre": "Science Fiction",
        "themes": ["identity", "family", "discovery"],
        "reading_level": "6-8",
        "pages": 240,
        "description": "In a seemingly perfect society without pain or conflict, a boy is chosen to inherit memories of the past and discovers the dark truth.",
    },
    {
        "title": "The Martian",
        "author": "Andy Weir",
        "genre": "Science Fiction",
        "themes": ["survival", "technology", "humor"],
        "reading_level": "9-12",
        "pages": 369,
        "description": "An astronaut stranded alone on Mars must use his wit and science skills to survive and signal Earth for rescue.",
    },
    {
        "title": "Ready Player One",
        "author": "Ernest Cline",
        "genre": "Science Fiction",
        "themes": ["technology", "adventure", "friendship"],
        "reading_level": "9-12",
        "pages": 374,
        "description": "In a dystopian future, a teenager hunts for an Easter egg hidden in a virtual reality world, competing against corporate villains for ultimate control.",
    },
    {
        "title": "The Wild Robot",
        "author": "Peter Brown",
        "genre": "Science Fiction",
        "themes": ["technology", "nature", "identity"],
        "reading_level": "3-5",
        "pages": 288,
        "description": "A robot shipwrecked on an island must learn to survive in the wilderness and becomes the adoptive mother of a gosling.",
    },
    {
        "title": "City of Ember",
        "author": "Jeanne DuPrau",
        "genre": "Science Fiction",
        "themes": ["adventure", "discovery", "survival"],
        "reading_level": "6-8",
        "pages": 270,
        "description": "Two children discover their underground city's lights are failing and race to decode ancient instructions to find a way out.",
    },
    # Mystery
    {
        "title": "Harriet the Spy",
        "author": "Louise Fitzhugh",
        "genre": "Mystery",
        "themes": ["friendship", "identity", "discovery"],
        "reading_level": "6-8",
        "pages": 300,
        "description": "Eleven-year-old Harriet keeps a secret notebook of observations about everyone she knows, until it falls into the wrong hands.",
    },
    {
        "title": "Holes",
        "author": "Louis Sachar",
        "genre": "Mystery",
        "themes": ["friendship", "redemption", "mystery"],
        "reading_level": "6-8",
        "pages": 233,
        "description": "Wrongly convicted Stanley Yelnats is sent to a brutal desert camp where boys dig holes all day, uncovering a mystery spanning generations.",
    },
    {
        "title": "From the Mixed-Up Files of Mrs. Basil E. Frankweiler",
        "author": "E.L. Konigsburg",
        "genre": "Mystery",
        "themes": ["adventure", "mystery", "family"],
        "reading_level": "6-8",
        "pages": 162,
        "description": "Two siblings run away from home and hide in the Metropolitan Museum of Art, where they investigate the mystery of a beautiful statue.",
    },
    {
        "title": "Chasing Vermeer",
        "author": "Blue Balliett",
        "genre": "Mystery",
        "themes": ["mystery", "friendship", "discovery"],
        "reading_level": "6-8",
        "pages": 254,
        "description": "Two sixth-graders use codes, puzzles, and a set of mysterious pentominoes to track down a stolen Vermeer painting.",
    },
    {
        "title": "The London Eye Mystery",
        "author": "Siobhan Dowd",
        "genre": "Mystery",
        "themes": ["mystery", "family", "identity"],
        "reading_level": "6-8",
        "pages": 322,
        "description": "A boy with a unique way of thinking must solve the mystery of his cousin who vanished from a sealed London Eye pod.",
    },
    {
        "title": "Encyclopedia Brown, Boy Detective",
        "author": "Donald J. Sobol",
        "genre": "Mystery",
        "themes": ["mystery", "friendship", "discovery"],
        "reading_level": "3-5",
        "pages": 88,
        "description": "Ten-year-old Leroy Brown runs a detective agency from his garage, solving neighborhood mysteries for just 25 cents a case.",
    },
    # Adventure
    {
        "title": "The Swiss Family Robinson",
        "author": "Johann David Wyss",
        "genre": "Adventure",
        "themes": ["survival", "family", "nature"],
        "reading_level": "6-8",
        "pages": 352,
        "description": "A shipwrecked family builds an incredible life on a deserted island, creating treehouses and discovering exotic animals.",
    },
    {
        "title": "My Side of the Mountain",
        "author": "Jean Craighead George",
        "genre": "Adventure",
        "themes": ["survival", "nature", "identity"],
        "reading_level": "6-8",
        "pages": 177,
        "description": "A boy runs away to the Catskill Mountains and survives alone in the wilderness with a falcon and a hollowed-out tree home.",
    },
    {
        "title": "Julie of the Wolves",
        "author": "Jean Craighead George",
        "genre": "Adventure",
        "themes": ["survival", "nature", "identity"],
        "reading_level": "6-8",
        "pages": 170,
        "description": "Lost on the Alaskan tundra, a young Inuit girl survives by communicating with and living among a pack of Arctic wolves.",
    },
    {
        "title": "Call of the Wild",
        "author": "Jack London",
        "genre": "Adventure",
        "themes": ["nature", "survival", "identity"],
        "reading_level": "9-12",
        "pages": 232,
        "description": "A domesticated dog is stolen and sold as a sled dog in the Yukon, where he must embrace his wild instincts to survive.",
    },
    {
        "title": "The Adventures of Tom Sawyer",
        "author": "Mark Twain",
        "genre": "Adventure",
        "themes": ["adventure", "friendship", "humor"],
        "reading_level": "9-12",
        "pages": 274,
        "description": "Follow mischievous Tom Sawyer through pranks, treasure hunts, and adventures along the Mississippi River with his friend Huckleberry Finn.",
    },
    {
        "title": "The Ranger's Apprentice",
        "author": "John Flanagan",
        "genre": "Adventure",
        "themes": ["adventure", "courage", "friendship"],
        "reading_level": "6-8",
        "pages": 249,
        "description": "An orphan becomes apprentice to a mysterious Ranger, learning the skills of stealth and survival to protect the kingdom.",
    },
    # Realistic Fiction
    {
        "title": "Wonder",
        "author": "R.J. Palacio",
        "genre": "Realistic Fiction",
        "themes": ["friendship", "identity", "courage"],
        "reading_level": "6-8",
        "pages": 315,
        "description": "Auggie, born with facial differences, navigates the challenges of starting school for the first time and shows everyone the power of kindness.",
    },
    {
        "title": "The Outsiders",
        "author": "S.E. Hinton",
        "genre": "Realistic Fiction",
        "themes": ["friendship", "identity", "family"],
        "reading_level": "9-12",
        "pages": 192,
        "description": "A group of working-class teens called the Greasers struggle with violence, loyalty, and growing up on the wrong side of town.",
    },
    {
        "title": "The Secret Garden",
        "author": "Frances Hodgson Burnett",
        "genre": "Realistic Fiction",
        "themes": ["friendship", "nature", "family"],
        "reading_level": "6-8",
        "pages": 331,
        "description": "A spoiled orphan discovers a hidden garden on her uncle's estate and its restoration transforms her and a sickly boy.",
    },
    {
        "title": "Because of Winn-Dixie",
        "author": "Kate DiCamillo",
        "genre": "Realistic Fiction",
        "themes": ["friendship", "family", "loss"],
        "reading_level": "3-5",
        "pages": 182,
        "description": "A lonely girl finds a scruffy dog at the supermarket, and together they make unexpected friends in their new small town.",
    },
    {
        "title": "The One and Only Ivan",
        "author": "Katherine Applegate",
        "genre": "Realistic Fiction",
        "themes": ["friendship", "identity", "heroism"],
        "reading_level": "3-5",
        "pages": 305,
        "description": "A gorilla living in a mall discovers his talent for art and makes a promise to save a baby elephant from their captivity.",
    },
    {
        "title": "Esperanza Rising",
        "author": "Pam Munoz Ryan",
        "genre": "Realistic Fiction",
        "themes": ["family", "identity", "courage"],
        "reading_level": "6-8",
        "pages": 262,
        "description": "A wealthy Mexican girl loses everything and must adapt to life as a farm laborer in Depression-era California.",
    },
    {
        "title": "Refugee",
        "author": "Alan Gratz",
        "genre": "Realistic Fiction",
        "themes": ["courage", "family", "survival"],
        "reading_level": "6-8",
        "pages": 338,
        "description": "Three children flee their homes in different eras - Nazi Germany, 1990s Cuba, and war-torn Syria - searching for safety and hope.",
    },
    {
        "title": "Ghost",
        "author": "Jason Reynolds",
        "genre": "Realistic Fiction",
        "themes": ["identity", "family", "courage"],
        "reading_level": "6-8",
        "pages": 180,
        "description": "A boy with a troubled past discovers his natural gift for running and must learn to channel his anger into becoming a track star.",
    },
    # Graphic Novels
    {
        "title": "New Kid",
        "author": "Jerry Craft",
        "genre": "Graphic Novel",
        "themes": ["identity", "friendship", "family"],
        "reading_level": "6-8",
        "pages": 256,
        "description": "Jordan Banks navigates being one of the few kids of color at a prestigious private school while pursuing his dream of being a cartoonist.",
    },
    {
        "title": "Smile",
        "author": "Raina Telgemeier",
        "genre": "Graphic Novel",
        "themes": ["identity", "coming-of-age", "family"],
        "reading_level": "6-8",
        "pages": 224,
        "description": "After a dental accident leaves her with injured front teeth, Raina faces years of braces, surgery, and middle school drama.",
    },
    {
        "title": "Dog Man",
        "author": "Dav Pilkey",
        "genre": "Graphic Novel",
        "themes": ["humor", "heroism", "friendship"],
        "reading_level": "3-5",
        "pages": 231,
        "description": "A superhero cop with the head of a dog and body of a policeman battles silly villains in hilarious comic adventures.",
    },
    {
        "title": "Amulet",
        "author": "Kazu Kibuishi",
        "genre": "Graphic Novel",
        "themes": ["adventure", "family", "magic"],
        "reading_level": "6-8",
        "pages": 192,
        "description": "After moving to an old house, two siblings discover a magical amulet and travel to a strange world to rescue their kidnapped mother.",
    },
    {
        "title": "Bone",
        "author": "Jeff Smith",
        "genre": "Graphic Novel",
        "themes": ["adventure", "humor", "heroism"],
        "reading_level": "6-8",
        "pages": 138,
        "description": "Three cartoon Bone cousins get lost in a mysterious valley filled with monsters, dragons, and an epic battle between good and evil.",
    },
    # Historical Fiction
    {
        "title": "Number the Stars",
        "author": "Lois Lowry",
        "genre": "Historical Fiction",
        "themes": ["courage", "friendship", "heroism"],
        "reading_level": "6-8",
        "pages": 137,
        "description": "A Danish girl risks her life to help her Jewish best friend escape the Nazis during World War II occupied Denmark.",
    },
    {
        "title": "The Book Thief",
        "author": "Markus Zusak",
        "genre": "Historical Fiction",
        "themes": ["love", "loss", "courage"],
        "reading_level": "9-12",
        "pages": 552,
        "description": "Narrated by Death, this is the story of a German girl who steals books and shares them while her family hides a Jewish man.",
    },
    {
        "title": "Inside Out and Back Again",
        "author": "Thanhha Lai",
        "genre": "Historical Fiction",
        "themes": ["family", "identity", "courage"],
        "reading_level": "6-8",
        "pages": 262,
        "description": "A Vietnamese girl flees Saigon in 1975 and struggles to adapt to a new life in Alabama, told through beautiful poems.",
    },
    {
        "title": "I Survived: The Sinking of the Titanic",
        "author": "Lauren Tarshis",
        "genre": "Historical Fiction",
        "themes": ["survival", "courage", "adventure"],
        "reading_level": "3-5",
        "pages": 112,
        "description": "A young boy exploring the Titanic gets separated from his family when the ship hits an iceberg and must fight to survive.",
    },
    {
        "title": "Chains",
        "author": "Laurie Halse Anderson",
        "genre": "Historical Fiction",
        "themes": ["courage", "identity", "heroism"],
        "reading_level": "6-8",
        "pages": 316,
        "description": "An enslaved girl in Revolutionary War New York becomes a spy for the rebels while fighting for her own freedom.",
    },
    # Non-Fiction/Biography
    {
        "title": "Hidden Figures (Young Readers' Edition)",
        "author": "Margot Lee Shetterly",
        "genre": "Biography",
        "themes": ["heroism", "identity", "discovery"],
        "reading_level": "6-8",
        "pages": 240,
        "description": "The true story of four Black women mathematicians whose calculations helped launch NASA's first astronauts into space.",
    },
    {
        "title": "I Am Malala (Young Readers' Edition)",
        "author": "Malala Yousafzai",
        "genre": "Biography",
        "themes": ["courage", "identity", "heroism"],
        "reading_level": "6-8",
        "pages": 240,
        "description": "A Pakistani girl defies the Taliban's ban on education and survives being shot to become the youngest Nobel Peace Prize winner.",
    },
    {
        "title": "The Boy Who Harnessed the Wind",
        "author": "William Kamkwamba",
        "genre": "Biography",
        "themes": ["discovery", "courage", "technology"],
        "reading_level": "6-8",
        "pages": 293,
        "description": "A Malawian teenager teaches himself engineering from library books and builds a windmill to save his village from famine.",
    },
    {
        "title": "Who Was Albert Einstein?",
        "author": "Jess Brallier",
        "genre": "Biography",
        "themes": ["discovery", "identity", "technology"],
        "reading_level": "3-5",
        "pages": 112,
        "description": "The life story of the wild-haired genius who revolutionized physics with his theories of relativity and E=mc².",
    },
    # Humor
    {
        "title": "Diary of a Wimpy Kid",
        "author": "Jeff Kinney",
        "genre": "Humor",
        "themes": ["humor", "friendship", "family"],
        "reading_level": "3-5",
        "pages": 217,
        "description": "Greg Heffley chronicles his misadventures through middle school in a hilarious illustrated diary full of schemes gone wrong.",
    },
    {
        "title": "Captain Underpants",
        "author": "Dav Pilkey",
        "genre": "Humor",
        "themes": ["humor", "friendship", "adventure"],
        "reading_level": "K-2",
        "pages": 121,
        "description": "Two prankster kids accidentally hypnotize their principal into becoming a superhero who fights crime in his underwear.",
    },
    {
        "title": "Flat Stanley",
        "author": "Jeff Brown",
        "genre": "Humor",
        "themes": ["humor", "adventure", "family"],
        "reading_level": "3-5",
        "pages": 64,
        "description": "After a bulletin board flattens him, Stanley discovers the perks of being paper-thin, like being mailed to visit friends.",
    },
    {
        "title": "The Bad Guys",
        "author": "Aaron Blabey",
        "genre": "Humor",
        "themes": ["humor", "friendship", "redemption"],
        "reading_level": "3-5",
        "pages": 144,
        "description": "A wolf, snake, piranha, and shark decide to stop being villains and become heroes, but nobody believes they've changed.",
    },
    # Animals
    {
        "title": "Charlotte's Web",
        "author": "E.B. White",
        "genre": "Animals",
        "themes": ["friendship", "love", "loss"],
        "reading_level": "3-5",
        "pages": 192,
        "description": "A clever spider named Charlotte weaves messages in her web to save her pig friend Wilbur from becoming bacon.",
    },
    {
        "title": "The Cricket in Times Square",
        "author": "George Selden",
        "genre": "Animals",
        "themes": ["friendship", "adventure", "love"],
        "reading_level": "6-8",
        "pages": 151,
        "description": "A musical cricket from Connecticut accidentally arrives in New York City's subway and befriends a mouse and cat.",
    },
    {
        "title": "Shiloh",
        "author": "Phyllis Reynolds Naylor",
        "genre": "Animals",
        "themes": ["friendship", "courage", "family"],
        "reading_level": "3-5",
        "pages": 144,
        "description": "A boy secretly hides an abused beagle from its cruel owner, struggling between honesty and protecting the dog he loves.",
    },
    {
        "title": "Warriors: Into the Wild",
        "author": "Erin Hunter",
        "genre": "Animals",
        "themes": ["adventure", "identity", "courage"],
        "reading_level": "6-8",
        "pages": 272,
        "description": "A house cat joins a clan of wild cats living in the forest and must prove his loyalty through dangerous battles.",
    },
    {
        "title": "The Incredible Journey",
        "author": "Sheila Burnford",
        "genre": "Animals",
        "themes": ["adventure", "survival", "love"],
        "reading_level": "6-8",
        "pages": 148,
        "description": "Two dogs and a cat travel 300 miles through the Canadian wilderness to find their way back home to their family.",
    },
    # Additional books to reach 100
    # K-2 Picture Books and Early Readers
    {
        "title": "The Very Hungry Caterpillar",
        "author": "Eric Carle",
        "genre": "Picture Book",
        "themes": ["nature", "discovery", "humor"],
        "reading_level": "K-2",
        "pages": 26,
        "description": "A tiny caterpillar eats through an enormous amount of food before transforming into a beautiful butterfly.",
    },
    {
        "title": "Where the Wild Things Are",
        "author": "Maurice Sendak",
        "genre": "Picture Book",
        "themes": ["adventure", "family", "identity"],
        "reading_level": "K-2",
        "pages": 48,
        "description": "Sent to bed without supper, a mischievous boy sails to an island where he becomes king of the wild monsters.",
    },
    {
        "title": "Goodnight Moon",
        "author": "Margaret Wise Brown",
        "genre": "Picture Book",
        "themes": ["family", "nature", "love"],
        "reading_level": "K-2",
        "pages": 32,
        "description": "A little bunny says goodnight to everything in his room in this soothing bedtime classic.",
    },
    {
        "title": "The Giving Tree",
        "author": "Shel Silverstein",
        "genre": "Picture Book",
        "themes": ["love", "friendship", "loss"],
        "reading_level": "K-2",
        "pages": 64,
        "description": "A tree gives everything it has to a boy throughout his life in this bittersweet story about love and sacrifice.",
    },
    {
        "title": "Green Eggs and Ham",
        "author": "Dr. Seuss",
        "genre": "Picture Book",
        "themes": ["humor", "friendship", "adventure"],
        "reading_level": "K-2",
        "pages": 62,
        "description": "Sam-I-Am persistently tries to convince a grumpy character to try green eggs and ham in every possible situation.",
    },
    {
        "title": "The Cat in the Hat",
        "author": "Dr. Seuss",
        "genre": "Picture Book",
        "themes": ["humor", "adventure", "friendship"],
        "reading_level": "K-2",
        "pages": 61,
        "description": "A mischievous cat in a tall striped hat brings chaos to two bored children on a rainy day.",
    },
    {
        "title": "Corduroy",
        "author": "Don Freeman",
        "genre": "Picture Book",
        "themes": ["friendship", "love", "identity"],
        "reading_level": "K-2",
        "pages": 32,
        "description": "A teddy bear in a department store searches for his lost button, hoping someone will buy him and give him a home.",
    },
    {
        "title": "If You Give a Mouse a Cookie",
        "author": "Laura Numeroff",
        "genre": "Picture Book",
        "themes": ["humor", "friendship", "adventure"],
        "reading_level": "K-2",
        "pages": 40,
        "description": "A mouse's request for a cookie leads to an endless chain of demands in this circular, humorous tale.",
    },
    # 3-5 Chapter Books
    {
        "title": "Magic Tree House: Dinosaurs Before Dark",
        "author": "Mary Pope Osborne",
        "genre": "Fantasy",
        "themes": ["adventure", "discovery", "friendship"],
        "reading_level": "3-5",
        "pages": 68,
        "description": "A magical treehouse transports siblings Jack and Annie back to the time of dinosaurs for their first adventure.",
    },
    {
        "title": "Junie B. Jones and the Stupid Smelly Bus",
        "author": "Barbara Park",
        "genre": "Humor",
        "themes": ["humor", "friendship", "coming-of-age"],
        "reading_level": "3-5",
        "pages": 69,
        "description": "Outspoken kindergartener Junie B. Jones decides to hide in school rather than ride the terrifying school bus home.",
    },
    {
        "title": "Ivy + Bean",
        "author": "Annie Barrows",
        "genre": "Realistic Fiction",
        "themes": ["friendship", "humor", "adventure"],
        "reading_level": "3-5",
        "pages": 128,
        "description": "Two very different girls become unlikely best friends after Bean needs Ivy's help hiding from her angry sister.",
    },
    {
        "title": "The Magic School Bus: Inside the Human Body",
        "author": "Joanna Cole",
        "genre": "Science",
        "themes": ["discovery", "technology", "adventure"],
        "reading_level": "3-5",
        "pages": 40,
        "description": "Ms. Frizzle shrinks the school bus and takes her class on a wild ride through a student's digestive system.",
    },
    {
        "title": "Frog and Toad Are Friends",
        "author": "Arnold Lobel",
        "genre": "Animals",
        "themes": ["friendship", "humor", "love"],
        "reading_level": "3-5",
        "pages": 64,
        "description": "A cheerful frog and a grumpy toad share gentle, funny adventures that celebrate their devoted friendship.",
    },
    {
        "title": "Ramona Quimby, Age 8",
        "author": "Beverly Cleary",
        "genre": "Realistic Fiction",
        "themes": ["family", "humor", "coming-of-age"],
        "reading_level": "3-5",
        "pages": 190,
        "description": "Spunky Ramona navigates the challenges of third grade while her family deals with changes and money troubles.",
    },
    {
        "title": "Stuart Little",
        "author": "E.B. White",
        "genre": "Fantasy",
        "themes": ["adventure", "family", "identity"],
        "reading_level": "3-5",
        "pages": 131,
        "description": "A mouse born to a human family in New York City sets off on an adventure to find his missing bird friend.",
    },
    # 6-8 Middle Grade
    {
        "title": "Matilda",
        "author": "Roald Dahl",
        "genre": "Fantasy",
        "themes": ["magic", "courage", "family"],
        "reading_level": "6-8",
        "pages": 240,
        "description": "A genius girl with terrible parents discovers she has telekinetic powers and uses them against her villainous headmistress.",
    },
    {
        "title": "The BFG",
        "author": "Roald Dahl",
        "genre": "Fantasy",
        "themes": ["friendship", "adventure", "courage"],
        "reading_level": "6-8",
        "pages": 208,
        "description": "A Big Friendly Giant who catches dreams befriends an orphan girl and together they stop the man-eating giants.",
    },
    {
        "title": "Charlie and the Chocolate Factory",
        "author": "Roald Dahl",
        "genre": "Fantasy",
        "themes": ["adventure", "family", "magic"],
        "reading_level": "6-8",
        "pages": 176,
        "description": "A poor boy wins a golden ticket to tour Willy Wonka's mysterious factory filled with candy wonders and Oompa-Loompas.",
    },
    {
        "title": "Tuck Everlasting",
        "author": "Natalie Babbitt",
        "genre": "Fantasy",
        "themes": ["love", "family", "identity"],
        "reading_level": "6-8",
        "pages": 144,
        "description": "A girl discovers a family that has lived forever after drinking from a magical spring and must protect their secret.",
    },
    {
        "title": "The Phantom Tollbooth",
        "author": "Norton Juster",
        "genre": "Fantasy",
        "themes": ["adventure", "discovery", "humor"],
        "reading_level": "6-8",
        "pages": 272,
        "description": "A bored boy drives a toy car through a magical tollbooth into a land where words and numbers come hilariously to life.",
    },
    {
        "title": "Maniac Magee",
        "author": "Jerry Spinelli",
        "genre": "Realistic Fiction",
        "themes": ["friendship", "identity", "courage"],
        "reading_level": "6-8",
        "pages": 184,
        "description": "A homeless boy becomes a legend in a divided town through his athletic feats and his ability to bring people together.",
    },
    # 9-12 Young Adult
    {
        "title": "The Hunger Games",
        "author": "Suzanne Collins",
        "genre": "Science Fiction",
        "themes": ["survival", "courage", "love"],
        "reading_level": "9-12",
        "pages": 374,
        "description": "In a dystopian future, a girl volunteers to take her sister's place in a televised fight to the death between children.",
    },
    {
        "title": "Divergent",
        "author": "Veronica Roth",
        "genre": "Science Fiction",
        "themes": ["identity", "courage", "love"],
        "reading_level": "9-12",
        "pages": 487,
        "description": "In a society divided into personality-based factions, a girl discovers she doesn't fit in anywhere and uncovers a conspiracy.",
    },
    {
        "title": "The Maze Runner",
        "author": "James Dashner",
        "genre": "Science Fiction",
        "themes": ["survival", "mystery", "friendship"],
        "reading_level": "9-12",
        "pages": 384,
        "description": "A boy wakes up with no memory in a maze filled with deadly creatures, along with dozens of other boys trying to escape.",
    },
    {
        "title": "The Fault in Our Stars",
        "author": "John Green",
        "genre": "Realistic Fiction",
        "themes": ["love", "loss", "identity"],
        "reading_level": "9-12",
        "pages": 313,
        "description": "Two teenagers with cancer fall in love and share an unforgettable journey that proves life isn't about how long you live.",
    },
    {
        "title": "Twilight",
        "author": "Stephenie Meyer",
        "genre": "Fantasy",
        "themes": ["love", "identity", "adventure"],
        "reading_level": "9-12",
        "pages": 498,
        "description": "A teenage girl moves to a small town and falls dangerously in love with a mysterious vampire who struggles with his nature.",
    },
    {
        "title": "The Perks of Being a Wallflower",
        "author": "Stephen Chbosky",
        "genre": "Realistic Fiction",
        "themes": ["coming-of-age", "friendship", "identity"],
        "reading_level": "9-12",
        "pages": 213,
        "description": "A shy freshman writes letters about navigating high school, first love, and mental health with his new artistic friends.",
    },
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "genre": "Historical Fiction",
        "themes": ["courage", "identity", "family"],
        "reading_level": "9-12",
        "pages": 324,
        "description": "A young girl watches her father, a lawyer, defend a Black man wrongly accused of a crime in 1930s Alabama.",
    },
    {
        "title": "The Hate U Give",
        "author": "Angie Thomas",
        "genre": "Realistic Fiction",
        "themes": ["identity", "courage", "family"],
        "reading_level": "9-12",
        "pages": 444,
        "description": "After witnessing a police officer shoot her unarmed friend, a Black teenager must find her voice and speak out for justice.",
    },
    {
        "title": "Six of Crows",
        "author": "Leigh Bardugo",
        "genre": "Fantasy",
        "themes": ["adventure", "friendship", "redemption"],
        "reading_level": "9-12",
        "pages": 465,
        "description": "A crew of six teenage outcasts attempts an impossible heist that could make them rich or destroy them all.",
    },
    # Final 8 books to reach 100
    {
        "title": "Chicka Chicka Boom Boom",
        "author": "Bill Martin Jr.",
        "genre": "Picture Book",
        "themes": ["humor", "discovery", "friendship"],
        "reading_level": "K-2",
        "pages": 36,
        "description": "The letters of the alphabet race each other up a coconut tree in this rhythmic, colorful celebration of ABCs.",
    },
    {
        "title": "Pete the Cat: I Love My White Shoes",
        "author": "Eric Litwin",
        "genre": "Picture Book",
        "themes": ["humor", "adventure", "friendship"],
        "reading_level": "K-2",
        "pages": 40,
        "description": "A cool cat walks through town stepping in colorful things, showing that no matter what, it's all good.",
    },
    {
        "title": "Geronimo Stilton: Lost Treasure of the Emerald Eye",
        "author": "Geronimo Stilton",
        "genre": "Adventure",
        "themes": ["adventure", "humor", "friendship"],
        "reading_level": "3-5",
        "pages": 128,
        "description": "A timid newspaper mouse is dragged on an adventure by his daredevil sister to find a legendary pirate treasure.",
    },
    {
        "title": "Cam Jansen and the Mystery of the Stolen Diamonds",
        "author": "David A. Adler",
        "genre": "Mystery",
        "themes": ["mystery", "friendship", "discovery"],
        "reading_level": "3-5",
        "pages": 64,
        "description": "A girl with a photographic memory uses her special skill to solve the case of diamonds stolen from a mall jewelry store.",
    },
    {
        "title": "The Tale of Despereaux",
        "author": "Kate DiCamillo",
        "genre": "Fantasy",
        "themes": ["courage", "love", "heroism"],
        "reading_level": "6-8",
        "pages": 272,
        "description": "A brave little mouse falls in love with a princess and must rescue her from the dungeon's darkness.",
    },
    {
        "title": "Coraline",
        "author": "Neil Gaiman",
        "genre": "Horror",
        "themes": ["courage", "family", "adventure"],
        "reading_level": "6-8",
        "pages": 162,
        "description": "A girl discovers a secret door to an alternate world with button-eyed parents who want to keep her forever.",
    },
    {
        "title": "Miss Peregrine's Home for Peculiar Children",
        "author": "Ransom Riggs",
        "genre": "Fantasy",
        "themes": ["mystery", "adventure", "identity"],
        "reading_level": "9-12",
        "pages": 352,
        "description": "A boy discovers a hidden world of children with extraordinary abilities, trapped in a time loop to escape monsters.",
    },
    {
        "title": "The Giver of Stars",
        "author": "Jojo Moyes",
        "genre": "Historical Fiction",
        "themes": ["friendship", "courage", "adventure"],
        "reading_level": "9-12",
        "pages": 400,
        "description": "Five women become traveling librarians on horseback in Depression-era Kentucky, delivering books through dangerous terrain.",
    },
]

# Shelf locations in 3D space (x, y, z coordinates in the library)
SHELF_SECTIONS = {
    "Fantasy": {"section": "A", "x_range": (0, 3), "y": 1.5, "z_range": (0, 2)},
    "Science Fiction": {"section": "A", "x_range": (3, 6), "y": 1.5, "z_range": (0, 2)},
    "Mystery": {"section": "B", "x_range": (0, 3), "y": 1.5, "z_range": (2, 4)},
    "Adventure": {"section": "B", "x_range": (3, 6), "y": 1.5, "z_range": (2, 4)},
    "Historical Fiction": {
        "section": "C",
        "x_range": (0, 3),
        "y": 1.5,
        "z_range": (4, 6),
    },
    "Realistic Fiction": {
        "section": "C",
        "x_range": (3, 6),
        "y": 1.5,
        "z_range": (4, 6),
    },
    "Graphic Novel": {"section": "D", "x_range": (0, 3), "y": 1.0, "z_range": (6, 8)},
    "Biography": {"section": "D", "x_range": (3, 6), "y": 1.5, "z_range": (6, 8)},
    "Humor": {"section": "E", "x_range": (0, 3), "y": 1.0, "z_range": (8, 10)},
    "Animals": {"section": "E", "x_range": (3, 6), "y": 1.5, "z_range": (8, 10)},
    "Science": {"section": "F", "x_range": (6, 9), "y": 1.5, "z_range": (0, 2)},
    "History": {"section": "F", "x_range": (6, 9), "y": 1.5, "z_range": (2, 4)},
    "Sports": {"section": "G", "x_range": (6, 9), "y": 1.5, "z_range": (4, 6)},
    "Horror": {"section": "G", "x_range": (6, 9), "y": 1.5, "z_range": (6, 8)},
    "Romance": {"section": "G", "x_range": (6, 9), "y": 1.5, "z_range": (8, 10)},
    "Picture Book": {"section": "H", "x_range": (0, 3), "y": 0.8, "z_range": (10, 12)},
}


def generate_book_id() -> str:
    """Generate a unique book ID."""
    return f"BOOK-{uuid.uuid4().hex[:8].upper()}"


def get_shelf_location(genre: str) -> Dict[str, Any]:
    """Generate a 3D shelf location for a book based on genre."""
    shelf_info = SHELF_SECTIONS.get(genre, SHELF_SECTIONS["Realistic Fiction"])

    x = random.uniform(*shelf_info["x_range"])
    y = shelf_info["y"] + random.uniform(-0.3, 0.3)  # Vary shelf height slightly
    z = random.uniform(*shelf_info["z_range"])

    row = random.randint(1, 5)
    shelf = random.randint(1, 4)

    return {
        "section": shelf_info["section"],
        "row": row,
        "shelf": shelf,
        "position_3d": {"x": round(x, 2), "y": round(y, 2), "z": round(z, 2)},
        "call_number": f"{shelf_info['section']}{row:02d}.{shelf:02d}",
    }


def generate_book_catalog() -> List[Dict[str, Any]]:
    """Generate the complete book catalog with IDs and locations."""
    catalog = []

    for book in BOOK_DATABASE:
        book_entry = {
            "book_id": generate_book_id(),
            "title": book["title"],
            "author": book["author"],
            "genre": book["genre"],
            "themes": book["themes"],
            "reading_level": book["reading_level"],
            "pages": book["pages"],
            "shelf_location": get_shelf_location(book["genre"]),
            "cover_url": f"/static/covers/{sanitize_filename(book['title'])}.jpg",
            "description": book["description"],
            "available_copies": random.randint(1, 5),
            "total_copies": random.randint(3, 8),
        }
        catalog.append(book_entry)

    return catalog


def generate_all_data(output_dir: str = "data"):
    """Generate the book catalog and save to a file."""
    os.makedirs(output_dir, exist_ok=True)

    logger.info("Generating book catalog...")
    catalog = generate_book_catalog()

    with open(os.path.join(output_dir, "book_catalog.json"), "w") as f:
        json.dump(catalog, f, indent=2)

    logger.info(f"Data generation complete: {len(catalog)} books")

    return catalog


if __name__ == "__main__":
    generate_all_data()
